index.test.js, package.json, shared/validate.test.js, tests/all.js
Started adding unit tests (#2)
=> A few unit tests

provider/googleProvider.js
This adds a more helpful error message for those that don't change the `project` value from the template in `serverless.yml`. It now says:
```bash
Error --------------------------------------------------
Error: Incorrect configuration. Please change the 'project' key in the 'provider' block in your Serverless config file.
```
The `serverless.yml` template looks like this:
```yml
provider:
name: google
runtime: nodejs
project: my-project
credentials: ~/.gcloud/keyfile.json
```
If you don't change the `project` value to the ID for your project, you'll get this error:
```bash
Error --------------------------------------------------
Error: Access Not Configured. Google Cloud Deployment Manager API has not been used in project 1043443670838 before or it is disabled. Enable it by visiting …
```
=> Add more helpful error message for improper config

package/lib/compileFunctions.js, package/lib/compileFunctions.test.js
Closes #94 
I added a new property to the `properties` object on the function template, when compiling the functions. The resulting value, an object, is the result of merging a `labels` property on the `provider` object and a `labels` property on the function object. The function object's `labels` object takes priority, overriding properties on the provider objects's `labels`.
If no `labels` properties are defined the result is an empty object.
Use the following `serverless.yml` file in association with the `google-nodejs` template, changing the credentials and project values as necessary.
```yaml
service: gcf-nodejs
provider:
name: google
runtime: nodejs
project: my-project
credentials: ~/.gcloud/keyfile.json
labels:
app: google-nodejs-example
test: provider-label
plugins:
- …
```
=> Add Google Cloud Platform Labels Support

package/lib/compileFunctions.js, package/lib/compileFunctions.test.js, shared/utils.js, shared/utils.test.js
Fix issues #113 and #112 
BREAKING CHANGE:
- defaults to `nodejs8` runtime
```
provider:
name: google
runtime: nodejs8
project: myapp
region: europe-west1
memorySize: 128
```
Results in:
=> feat: nodejs8 runtime

package/lib/compileFunctions.js, package/lib/compileFunctions.test.js
Add support for passing environment variables to a function
=> feat: add support for environment variables in Cloud Functions

shared/utils.js, shared/utils.test.js
New regions are officially available outside US. 
https://cloud.google.com/functions/docs/locations
PR #43 was removed before because of issue https://github.com/serverless/serverless/issues/3332. Serverless framework hard-coding us-east-1 region which does not exist in GCF. 
This PR ignores this region, replacing to default region `us-central1`
=> Add provider based region support

provider/googleProvider.js
Support to use the GOOGLE_APPLICATION_CREDENTIALS environment variable instead of the provider credentials parameters as described in #122.
=> support GOOGLE_APPLICATION_CREDENTIALS env variable

shared/monitorDeployment.js
This fixes a bug where the deployment itself was legitimately failing, but the error handling itself failed.
Specifically, I noticed that the error being thrown was unnecessarily hiding the actual error, which obfuscated the real issue. The real issue was that the error message was expected to return valid JSON, but it was pseudo-JSON instead (no surrounding `{}`). By removing the redundant JSON.stringify(JSON.parse(...)) wrapping of the message I was able to see the actual issue in my case:
> "/httpsTrigger/url": domain: validation; keyword: type; message: instance does not match any allowed primitive type; allowed: ["string"]; found: "object"
which allowed me to realize that what I had done in the past with AWS Lambda was not valid for GCP Cloud Functions (specifically specifying the …
=> Fix Unexpected token : in JSON

provider/googleProvider.js, provider/googleProvider.test.js
Sets the options config before storing the used service instances in the `this.sdk` object.
/cc @brianneisler
=> Set google options config

provider/googleProvider.js
Fixes the lookup of the `googleapis` module version by using `require.resolve`.
/cc @brianneisler
=> Fix googleapis version lookup

package/lib/compileFunctions.js, package/lib/compileFunctions.test.js
Do not overwrite `serverless.service.provider.environment` property on `compileFunctions()`.
See https://lodash.com/docs/4.17.11#merge
> Note: This method mutates object.
- Check merge priority, variable is updated by function's `environment` property.
- `serverless.service.provider.environment` isn't overwritten after `compileFunctions()` .
- #167 
- #162 : This fixes same issue. I also made tests to check specification.
=> Fix lodash merge function not to update original object.

package/lib/compileFunctions.js, package/lib/compileFunctions.test.js
This PR include below changes:
1. Add GCP vpc support
2. Fix the unit test in compileFunction.test.js 
Related Issue:
https://github.com/serverless/serverless-google-cloudfunctions/issues/190
Other reference:
https://cloud.google.com/functions/docs/connecting-vpc
https://github.com/googleapis/google-api-nodejs-client/blob/master/src/apis/cloudfunctions/v1.ts#L272
=> GCP VPC Support and Unit Test fix

invoke/lib/invokeFunction.js, invoke/lib/invokeFunction.test.js
When calling `invoke`, the function name is not correct, giving a `Function XXX (…) does not exist` error. This is because the function _handler_ was used instead of the function _name_.
Fixes #212
Fixes #213
=> Fix function name on invoke

package/lib/compileFunctions.js, package/lib/compileFunctions.test.js
This  PR:
- adds the ability to set IAM policies for functions
- adds a `allowUnauthenticated` property to a function as a shortcut for adding the `roles/cloudfunctions.invoker` role for `allUsers`, making the function public (see:  https://cloud.google.com/functions/docs/securing/managing-access-iam#gcloud_4)
- adds test cases for the above
Note that I haven't tested this with an actual deploy because I'm not sure how use my fork of this plugin in a serverless configuration, but I can look into how to get that set up tomorrow.
Relates to:
- #205
- #179
=> feat: add support for allowUnauthenticated and custom IAM definitions

package/lib/prepareDeployment.js, package/lib/prepareDeployment.test.js
This is a basic correction for the issue https://github.com/serverless/serverless-google-cloudfunctions/issues/226
Tell me if I can do something better !
Note that this PR is similar to https://github.com/serverless/serverless-google-cloudfunctions/pull/220
=> fix: Deploy bucket in configured location

info/lib/displayServiceInfo.js, info/lib/displayServiceInfo.test.js, test/serverless.js
* fixes the logic to get the function name in service
* handles the case when the specified function name contains dash
* adds test case
=> fix: Fix deployment status when the function name is specified

package/googlePackage.js, package/googlePackage.test.js, provider/googleProvider.js, provider/googleProvider.test.js, test/serverless.js
Fixes https://github.com/serverless/serverless-google-cloudfunctions/issues/232
Validate the serverless configuration for `google` provider and the configuration of the two triggers of cloud functions (`http` and `event`) 
I didn't find any test in integration with the `serverless` package so I tested it manually.
`yarn sls package` with this configuration doesn't output any warning
```
service: test-schema-validation
frameworkVersion: '2'
plugins:
- serverless-google-cloudfunctions
provider:
name: google
stage: dev
runtime: nodejs10
region: us-central1
project: my-project
credentials: ~/.gcloud/keyfile.json
serviceAccountEmail: 'email'
memorySize: 512
timeout: 90s
environment:
ENV_VAR_KEY: ENV_VAR_VALUE
vpc: projects/{project_id}/locations/{region}/connectors/{connector_name}
labels: …
```
=> feat: Add schema validation

logs/googleLogs.js, logs/googleLogs.test.js, logs/lib/retrieveLogs.js, logs/lib/retrieveLogs.test.js
Closes https://github.com/serverless/serverless-google-cloudfunctions/issues/256
Possible options are:
- string
- boolean
- multiple (strings)
I selected "string" and added a `parseInt` to handle the option correctly internally. Let me know if I should go a different direction!
=> fix: CLI option `count` type deprecation warning

.travis.yml
Do not run tests against Node 8 as it's no longer supported
=> chore: Do not run CI tests against Node 8

index.js, invokeLocal/googleInvokeLocal.js, invokeLocal/googleInvokeLocal.test.js, invokeLocal/lib/getDataAndContext.js, invokeLocal/lib/getDataAndContext.test.js, invokeLocal/lib/nodeJs.js, invokeLocal/lib/nodeJs.test.js, invokeLocal/lib/testMocks/index.js, package.json, package/lib/compileFunctions.js, provider/googleProvider.js, provider/googleProvider.test.js, shared/utils.js, shared/utils.test.js, shared/validate.js, shared/validate.test.js, test/serverless.js
This pull request adds the implementation of the command `invoke local` for the `google` provider. It's inspired by the AWS implementation to keep the behaviors as close as possible. 
The command is available for the `nodejs` runtimes and events of type `event`
PR merged to fix it: https://github.com/serverless-heaven/serverless-webpack/pull/834
- Add support for `http` events
=> feat: Add support for invoke local

invokeLocal/googleInvokeLocal.js, invokeLocal/googleInvokeLocal.test.js, invokeLocal/lib/httpReqRes.js, invokeLocal/lib/nodeJs.js, invokeLocal/lib/nodeJs.test.js, invokeLocal/lib/testMocks/index.js, package.json
This pull request follows https://github.com/serverless/serverless-google-cloudfunctions/pull/258 and adds the implementation of the command invoke local for HTTP events from the google provider.
[Cloud functions triggered by HTTP use express 4.17.1.](https://cloud.google.com/functions/docs/writing/http#http_frameworks)
1. Default `req` and `res` are recreated as they are provided by express to the handler in the cloud
2. The content of req is overridden by the data provided for the local execution
3. The `end` method of `res` is overridden by a custom method to 
1. prevent the default behavior of `end` (send back the response to the client) 
2. get the body of the response to logging it
3. end the local invocation 
- Document the usage of the command: …
=> feat: Add support for http events in invoke local

provider/googleProvider.js
Python 3.9 is generally available and is the recommended Python runtime: https://cloud.google.com/functions/docs/concepts/python-runtime
=> Added support for python39 runtime

package.json, provider/googleProvider.js
Additionally documented compatibility with Serverless Framework versions. I decided no to mark v1 as compatible, as since of release of v2, this plugin had two major releases, and dropped support for Node.js versions supported by v1
=> Support new variables resolver

package/lib/compileFunctions.js, package/lib/compileFunctions.test.js, provider/googleProvider.js
- Adds test covering minInstances
- Updates google provider schema to support minInstances 
- resolves #275
=> - Add support of GCP minInstances

provider/googleProvider.js
The Node.js 16 Runtime is available and recommended by Google.
https://cloud.google.com/functions/docs/concepts/nodejs-runtime
The Go 1.16 is available and recommended by Google.
https://cloud.google.com/functions/docs/concepts/go-runtime
=> feat: Add support for Node.js 16 and Go 1.16 Runtimes

package/lib/compileFunctions.js, package/lib/compileFunctions.test.js, provider/googleProvider.js
Add support for setting environment variables that pull from Secrets Manager.
I basically copied the pattern that environment variables are currently being set so would appreciate anything I've missed.
=> feat: Add support for secrets manager environment variables
